# Car Pricing Prediction

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r'C:\Users\HP\anaconda3\Machine Learning\e2e\Car Pricing\CarPrice.csv')

In [3]:
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

### Removing unwanted columns:-

In [30]:
df1=df.drop(['car_ID','symboling'], axis=1)

In [31]:
df1

,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,audi 100ls,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [32]:
df1.shape

(205, 24)

In [33]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CarName           205 non-null    object
 1   fueltype          205 non-null    object
 2   aspiration        205 non-null    object
 3   doornumber        205 non-null    object
 4   carbody           205 non-null    object
 5   drivewheel        205 non-null    object
 6   enginelocation    205 non-null    object
 7   wheelbase         205 non-null    float64
 8   carlength         205 non-null    float64
 9   carwidth          205 non-null    float64
 10  carheight         205 non-null    float64
 11  curbweight        205 non-null    int64
 12  enginetype        205 non-null    object
 13  cylindernumber    205 non-null    object
 14  enginesize        205 non-null    int64
 15  fuelsystem        205 non-null    object
 16  boreratio         205 non-null    float64
 17  stroke            205 non-null    float64
 18  compressionratio  205 non-null    float64
 19  horsepower        205 non-null    int64
 20  peakrpm           205 non-null    int64
 21  citympg           205 non-null    int64
 22  highwaympg        205 non-null    int64
 23  price             205 non-null    float64
dtypes: float64(8), int64(6), object(10)
memory usage: 38.6+ KB

In [7]:
data.describe()

,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,3.329756,3.255415,10.142537,104.117073,5125.121951,25.219512,30.751220,13276.710571
std,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,0.270844,0.313597,3.972040,39.544167,476.985643,6.542142,6.886443,7988.852332
min,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16503.000000
max,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

### checking missing values in data:-

In [34]:
missing=df1.isnull()

In [35]:
missing.sum()

CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

### **As we can see there is no null values in it so we can proceed for further steps.**

In [36]:
categorical_data= df1.select_dtypes(exclude=np.number)

In [37]:
categorical_data

,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,enginetype,cylindernumber,fuelsystem
0,alfa-romero giulia,gas,std,two,convertible,rwd,front,dohc,four,mpfi
1,alfa-romero stelvio,gas,std,two,convertible,rwd,front,dohc,four,mpfi
2,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,ohcv,six,mpfi
3,audi 100 ls,gas,std,four,sedan,fwd,front,ohc,four,mpfi
4,audi 100ls,gas,std,four,sedan,4wd,front,ohc,five,mpfi
...,...,...,...,...,...,...,...,...,...,...
200,volvo 145e (sw),gas,std,four,sedan,rwd,front,ohc,four,mpfi
201,volvo 144ea,gas,turbo,four,sedan,rwd,front,ohc,four,mpfi
202,volvo 244dl,gas,std,four,sedan,rwd,front,ohcv,six,mpfi
203,volvo 246,diesel,turbo,four,sedan,rwd,front,ohc,six,idi
204,volvo 264gl,gas,turbo,four,sedan,rwd,front,ohc,four,mpfi

In [38]:
dummies=pd.get_dummies(categorical_data, drop_first=True)

In [39]:
dummies

,CarName_alfa-romero Quadrifoglio,CarName_alfa-romero giulia,CarName_alfa-romero stelvio,CarName_audi 100 ls,CarName_audi 100ls,CarName_audi 4000,CarName_audi 5000,CarName_audi 5000s (diesel),CarName_audi fox,CarName_bmw 320i,...,cylindernumber_three,cylindernumber_twelve,cylindernumber_two,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
201,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
202,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
203,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
204,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [42]:
numeric=df1.select_dtypes(np.number)

In [43]:
numeric

,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27,13495.0
1,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27,16500.0
2,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,154,5000,19,26,16500.0
3,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,102,5500,24,30,13950.0
4,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,109.1,188.8,68.9,55.5,2952,141,3.78,3.15,9.5,114,5400,23,28,16845.0
201,109.1,188.8,68.8,55.5,3049,141,3.78,3.15,8.7,160,5300,19,25,19045.0
202,109.1,188.8,68.9,55.5,3012,173,3.58,2.87,8.8,134,5500,18,23,21485.0
203,109.1,188.8,68.9,55.5,3217,145,3.01,3.40,23.0,106,4800,26,27,22470.0
204,109.1,188.8,68.9,55.5,3062,141,3.78,3.15,9.5,114,5400,19,25,22625.0

In [47]:
data=pd.concat([dummies,numeric],axis=1)

In [48]:
data

,CarName_alfa-romero Quadrifoglio,CarName_alfa-romero giulia,CarName_alfa-romero stelvio,CarName_audi 100 ls,CarName_audi 100ls,CarName_audi 4000,CarName_audi 5000,CarName_audi 5000s (diesel),CarName_audi fox,CarName_bmw 320i,...,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,0,1,0,0,0,0,0,0,0,0,...,2548,130,3.47,2.68,9.0,111,5000,21,27,13495.0
1,0,0,1,0,0,0,0,0,0,0,...,2548,130,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,0,0,0,0,0,0,0,0,0,...,2823,152,2.68,3.47,9.0,154,5000,19,26,16500.0
3,0,0,0,1,0,0,0,0,0,0,...,2337,109,3.19,3.40,10.0,102,5500,24,30,13950.0
4,0,0,0,0,1,0,0,0,0,0,...,2824,136,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,0,0,0,0,0,0,0,0,0,0,...,2952,141,3.78,3.15,9.5,114,5400,23,28,16845.0
201,0,0,0,0,0,0,0,0,0,0,...,3049,141,3.78,3.15,8.7,160,5300,19,25,19045.0
202,0,0,0,0,0,0,0,0,0,0,...,3012,173,3.58,2.87,8.8,134,5500,18,23,21485.0
203,0,0,0,0,0,0,0,0,0,0,...,3217,145,3.01,3.40,23.0,106,4800,26,27,22470.0
204,0,0,0,0,0,0,0,0,0,0,...,3062,141,3.78,3.15,9.5,114,5400,19,25,22625.0

In [49]:
data.columns

Index(['CarName_alfa-romero Quadrifoglio', 'CarName_alfa-romero giulia',
       'CarName_alfa-romero stelvio', 'CarName_audi 100 ls',
       'CarName_audi 100ls', 'CarName_audi 4000', 'CarName_audi 5000',
       'CarName_audi 5000s (diesel)', 'CarName_audi fox', 'CarName_bmw 320i',
       ...
       'curbweight', 'enginesize', 'boreratio', 'stroke', 'compressionratio',
       'horsepower', 'peakrpm', 'citympg', 'highwaympg', 'price'],
      dtype='object', length=189)

In [51]:
data.corr()

,CarName_alfa-romero Quadrifoglio,CarName_alfa-romero giulia,CarName_alfa-romero stelvio,CarName_audi 100 ls,CarName_audi 100ls,CarName_audi 4000,CarName_audi 5000,CarName_audi 5000s (diesel),CarName_audi fox,CarName_bmw 320i,...,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
CarName_alfa-romero Quadrifoglio,1.000000,-0.004902,-0.004902,-0.004902,-0.006949,-0.004902,-0.004902,-0.004902,-0.004902,-0.006949,...,0.036049,0.042292,-0.168375,0.048026,-0.020188,0.088535,-0.018411,-0.066724,-0.048424,0.028318
CarName_alfa-romero giulia,-0.004902,1.000000,-0.004902,-0.004902,-0.006949,-0.004902,-0.004902,-0.004902,-0.004902,-0.006949,...,-0.001020,0.005212,0.036342,-0.128782,-0.020188,0.012216,-0.018411,-0.045268,-0.038232,0.001918
CarName_alfa-romero stelvio,-0.004902,-0.004902,1.000000,-0.004902,-0.006949,-0.004902,-0.004902,-0.004902,-0.004902,-0.006949,...,-0.001020,0.005212,0.036342,-0.128782,-0.020188,0.012216,-0.018411,-0.045268,-0.038232,0.028318
CarName_audi 100 ls,-0.004902,-0.004902,-0.004902,1.000000,-0.006949,-0.004902,-0.004902,-0.004902,-0.004902,-0.006949,...,-0.029462,-0.030181,-0.036216,0.032359,-0.002519,-0.003758,0.055161,-0.013083,-0.007656,0.005915
CarName_audi 100ls,-0.006949,-0.006949,-0.006949,-0.006949,1.000000,-0.006949,-0.006949,-0.006949,-0.006949,-0.009852,...,0.053208,0.021726,-0.051343,0.045876,-0.047409,0.021093,0.078201,-0.102199,-0.104772,0.053598
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
horsepower,0.088535,0.012216,0.012216,-0.003758,0.021093,0.063687,0.010441,0.099184,0.010441,-0.007843,...,0.750739,0.809769,0.573677,0.080940,-0.204326,1.000000,0.131073,-0.801456,-0.770544,0.808139
peakrpm,-0.018411,-0.018411,-0.018411,0.055161,0.078201,0.055161,0.055161,0.055161,0.055161,0.140783,...,-0.266243,-0.244660,-0.254976,-0.067964,-0.435741,0.131073,1.000000,-0.113544,-0.054275,-0.085267
citympg,-0.066724,-0.045268,-0.045268,-0.013083,-0.102199,-0.088181,-0.066724,-0.098909,-0.066724,-0.033757,...,-0.757414,-0.653658,-0.584532,-0.042145,0.324701,-0.801456,-0.113544,1.000000,0.971337,-0.685751
highwaympg,-0.048424,-0.038232,-0.038232,-0.007656,-0.104772,-0.109575,-0.058615,-0.089191,-0.058615,-0.025303,...,-0.797465,-0.677470,-0.587012,-0.043931,0.265201,-0.770544,-0.054275,0.971337,1.000000,-0.697599
price,0.028318,0.001918,0.028318,0.005915,0.053598,0.093110,0.049579,0.040259,0.017336,0.042357,...,0.835305,0.874145,0.553173,0.079443,0.067984,0.808139,-0.085267,-0.685751,-0.697599,1.000000

In [87]:
x=data.drop(['price'],axis=1)

In [88]:
x

,CarName_alfa-romero Quadrifoglio,CarName_alfa-romero giulia,CarName_alfa-romero stelvio,CarName_audi 100 ls,CarName_audi 100ls,CarName_audi 4000,CarName_audi 5000,CarName_audi 5000s (diesel),CarName_audi fox,CarName_bmw 320i,...,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
0,0,1,0,0,0,0,0,0,0,0,...,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27
1,0,0,1,0,0,0,0,0,0,0,...,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27
2,1,0,0,0,0,0,0,0,0,0,...,52.4,2823,152,2.68,3.47,9.0,154,5000,19,26
3,0,0,0,1,0,0,0,0,0,0,...,54.3,2337,109,3.19,3.40,10.0,102,5500,24,30
4,0,0,0,0,1,0,0,0,0,0,...,54.3,2824,136,3.19,3.40,8.0,115,5500,18,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,0,0,0,0,0,0,0,0,0,0,...,55.5,2952,141,3.78,3.15,9.5,114,5400,23,28
201,0,0,0,0,0,0,0,0,0,0,...,55.5,3049,141,3.78,3.15,8.7,160,5300,19,25
202,0,0,0,0,0,0,0,0,0,0,...,55.5,3012,173,3.58,2.87,8.8,134,5500,18,23
203,0,0,0,0,0,0,0,0,0,0,...,55.5,3217,145,3.01,3.40,23.0,106,4800,26,27
204,0,0,0,0,0,0,0,0,0,0,...,55.5,3062,141,3.78,3.15,9.5,114,5400,19,25

In [89]:
y=data['price']

In [90]:
y

0      13495.0
1      16500.0
2      16500.0
3      13950.0
4      17450.0
        ...
200    16845.0
201    19045.0
202    21485.0
203    22470.0
204    22625.0
Name: price, Length: 205, dtype: float64

In [91]:
from sklearn.preprocessing import StandardScaler

In [92]:
sc= StandardScaler()

In [94]:
dk=sc.fit_transform(x)

In [95]:
dk.shape

(205, 188)

In [96]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=100)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model= LinearRegression()

In [ ]:
model.fit(x_train,y_train)

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(y_test,y_pred)

In [ ]:
import pickle

In [ ]:
file = open('modelcar.pkl','wb')

In [ ]:
pickle.dump(model,file)